application: mikelwarddotcom
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: '/static'
  static_dir: 'static'
- url: '/styles'
  static_dir: 'styles'
- url: '/.*'
  script: 'app.application'
