application: mikelwarddotcom
version: 9
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: '/static'
  static_dir: 'static'
- url: '/styles'
  static_dir: 'styles'
- url: '/.well-known/acme-challenge'
  static_dir: 'acme-challenge'
- url: '/.*'
  script: 'app.application'
